name: Test Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 签出代码
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          id: get-project
      - name: 获取项目
        run: echo "::set-output name=PROJECT::$(cat project-to-build)"
      - name: 克隆项目
        run: git clone --depth=1 ${{ steps.get-project.outputs.PROJECT }} project
      - name: 构建应用程序
        working-directory: ./project
        run: |
          if [ ! -f "gradlew" ]; then gradle wrapper; fi
          chmod +x gradlew
          ./gradlew assembleDebug --stacktrace
      - name: 上传APK
        uses: actions/upload-artifact@v2
        with:
          name: TVbox
          path: ./**/*.apk

